# Generated by Django 3.0.8 on 2020-07-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vakansiya', 'verbose_name_plural': 'Vakansiyalar'},
        ),
    ]
