# Generated by Django 3.0.8 on 2020-07-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20200724_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='dead_line',
            field=models.DateField(verbose_name='Bitmə tarixi (YYYY-MM-DD)'),
        ),
    ]
