# Generated by Django 3.0.8 on 2020-08-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_comment_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment_1',
        ),
    ]
