# Generated by Django 3.0.4 on 2021-06-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_delete_comment_1'),
        ('blog', '0002_remove_comment_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vacancy.Vacancy'),
        ),
    ]
